/// [Fato] Subconjunto das manifestações cuja resposta foi avaliada como insatisfatória pela equipe da ouvidoria. Uma linha por resposta reprovada na revisão de qualidade. Base do KRI de respostas insatisfatórias.
table f_insatisfatorias
	lineageTag: 04ca9373-3d14-478c-8274-88ed004c9eab

	/// [Papel: Chave estrangeira] Protocolo da manifestação cuja resposta foi avaliada como insatisfatória. Relaciona f_insatisfatorias à tabela central f_relatorio.
	column protocolo
		dataType: string
		lineageTag: 4f5918c8-ad0b-423b-8077-d71f09071db0
		summarizeBy: none
		sourceColumn: protocolo

		annotation SummarizationSetBy = Automatic

	/// Data de registro da manifestação. Permite análise temporal da incidência de respostas insatisfatórias.
	column data_manifestacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 9931e0e0-6f16-473e-937e-b05764b4ff06
		summarizeBy: none
		sourceColumn: data_manifestacao

		annotation SummarizationSetBy = Automatic

	/// Data de finalização da manifestação cuja resposta foi reprovada.
	column data_finalizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c46c6e5-9e9b-4f0d-b552-46f1adb2128a
		summarizeBy: none
		sourceColumn: data_finalizacao

		variation Variation
			isDefault
			relationship: fee769f1-c1b0-4204-b0d9-fb10a002a560
			defaultHierarchy: LocalDateTable_19139d03-23fa-4bfa-91e8-4fe9100c0b7c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	/// Data da revisão que identificou a resposta como insatisfatória.
	column data_revisao
		dataType: dateTime
		formatString: General Date
		lineageTag: a8cfe85e-3afb-4c3f-a7a3-4b3067eaa84c
		summarizeBy: none
		sourceColumn: data_revisao

		variation Variation
			isDefault
			relationship: 91bf71e0-af8f-4402-8d08-be6f19fcc249
			defaultHierarchy: LocalDateTable_89d62a24-1048-4894-9db0-6307d404f36e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	/// Sigla do órgão responsável pela resposta avaliada como insatisfatória.
	column sigla
		dataType: string
		lineageTag: ff6fd93f-8c70-4872-9293-7859c8fb3826
		summarizeBy: none
		sourceColumn: sigla

		annotation SummarizationSetBy = Automatic

	/// Indicação de sigilo da manifestação com resposta reprovada.
	column sigilo
		dataType: string
		lineageTag: cfbcaba4-7849-43a2-a1a0-2c694d54a28f
		summarizeBy: none
		sourceColumn: sigilo

		annotation SummarizationSetBy = Automatic

	/// Dias de tramitação da manifestação com resposta insatisfatória.
	column dias_vida
		dataType: int64
		formatString: 0
		lineageTag: 85243afb-fb39-4e53-9500-eba537f3cdb8
		summarizeBy: sum
		sourceColumn: dias_vida

		annotation SummarizationSetBy = Automatic

	/// Dias após reativação, quando aplicável.
	column dias_reativacao
		dataType: int64
		formatString: 0
		lineageTag: 73f4e609-dd7b-441e-ad84-7e0206db41da
		summarizeBy: sum
		sourceColumn: dias_reativacao

		annotation SummarizationSetBy = Automatic

	/// [Papel: Métrica de linha] Dias de atraso em relação ao prazo da manifestação com resposta insatisfatória. Campo numérico nesta tabela; em f_relatorio o campo equivalente está como texto.
	column dias_atraso
		dataType: int64
		formatString: 0
		lineageTag: 3774e373-f2c2-4b15-a2aa-a364d4c8de62
		summarizeBy: sum
		sourceColumn: dias_atraso

		annotation SummarizationSetBy = Automatic

	/// Tipo da manifestação com resposta insatisfatória. Reclamações concentram a maior parte dos casos (68% do total).
	column tipo_manifestacao
		dataType: string
		lineageTag: 5c21f023-fa6d-461a-9fe4-96ddb829be5a
		summarizeBy: none
		sourceColumn: tipo_manifestacao

		annotation SummarizationSetBy = Automatic

	/// Município de origem da manifestação com resposta insatisfatória.
	column municipio
		dataType: string
		lineageTag: 6683bfec-73b3-41c6-baf2-a547182b1904
		summarizeBy: none
		sourceColumn: municipio

		annotation SummarizationSetBy = Automatic

	/// Assunto da manifestação com resposta reprovada. Permite identificar temas com maior dificuldade de atendimento.
	column tipificacao
		dataType: string
		lineageTag: 5aa37a83-5bab-4fa1-a10a-ab262d414550
		summarizeBy: none
		sourceColumn: tipificacao

		annotation SummarizationSetBy = Automatic

	/// Detalhamento do assunto dentro da tipificação, para análise de segundo nível das falhas de atendimento.
	column sub_tipificacao
		dataType: string
		lineageTag: adf438c3-0a5f-4156-8af9-1d5776eea59b
		summarizeBy: none
		sourceColumn: sub_tipificacao

		annotation SummarizationSetBy = Automatic

	column Id_manifestacao
		dataType: string
		lineageTag: 8f129138-c430-4e31-ac89-a76d13c0cc86
		summarizeBy: none
		sourceColumn: Id_manifestacao

		annotation SummarizationSetBy = Automatic

	column Suborgao
		dataType: string
		lineageTag: ef189ecb-8609-4b14-b0ab-5e087d1b84df
		summarizeBy: none
		sourceColumn: Suborgao

		annotation SummarizationSetBy = Automatic

	column Prazo_interno
		dataType: string
		lineageTag: 6857c056-73b4-4cb5-aa51-99cb32fdf6e4
		summarizeBy: none
		sourceColumn: Prazo_interno

		annotation SummarizationSetBy = Automatic

	column Prazo_externo
		dataType: string
		lineageTag: 29382688-179c-4815-a911-177fd1dd2080
		summarizeBy: none
		sourceColumn: Prazo_externo

		annotation SummarizationSetBy = Automatic

	column Area_tecnica
		dataType: string
		lineageTag: 8b037a1f-0393-4be8-8d41-ca42faa7b1be
		summarizeBy: none
		sourceColumn: Area_tecnica

		annotation SummarizationSetBy = Automatic

	column Registro
		dataType: string
		lineageTag: 88cb6f59-94dd-4089-84f8-c141ff95ff35
		summarizeBy: none
		sourceColumn: Registro

		annotation SummarizationSetBy = Automatic

	column Ds_status
		dataType: string
		lineageTag: 54b35ac3-cfb4-4b9e-957b-a13078a54fc1
		summarizeBy: none
		sourceColumn: Ds_status

		annotation SummarizationSetBy = Automatic

	column Publicacao
		dataType: string
		lineageTag: f6d3d5d1-67bc-4a46-b7b5-26c3093ab9b5
		summarizeBy: none
		sourceColumn: Publicacao

		annotation SummarizationSetBy = Automatic

	column Procedente
		dataType: string
		lineageTag: c777ad79-510d-4d92-8bf4-3406ae887c0a
		summarizeBy: none
		sourceColumn: Procedente

		annotation SummarizationSetBy = Automatic

	column Recurso
		dataType: string
		lineageTag: 6740f178-b485-4d14-8990-481d2d6350f7
		summarizeBy: none
		sourceColumn: Recurso

		annotation SummarizationSetBy = Automatic

	column Nm_sei
		dataType: string
		lineageTag: 72751c10-23d2-428c-bed6-81af13041c40
		summarizeBy: none
		sourceColumn: Nm_sei

		annotation SummarizationSetBy = Automatic

	partition f_insatisfatorias = m
		mode: import
		source =
				let
				    // Caminho da pasta de entrada
				    CaminhoPasta =
				        fnCaminhoEntrada(),
				
				    // Caminho completo do arquivo
				    CaminhoArquivo =
				        if Text.EndsWith(CaminhoPasta, "\") or Text.EndsWith(CaminhoPasta, "/")
				        then CaminhoPasta & "f_insatisfatorias.parquet"
				        else CaminhoPasta & "\f_insatisfatorias.parquet",
				
				    // Carregar arquivo Parquet
				    Fonte =
				        Parquet.Document(
				            File.Contents(CaminhoArquivo)
				        ),
				
				    // Renomear colunas para padrão minúsculo
				    ColunasRenomeadas =
				        Table.RenameColumns(
				            Fonte,
				            {
				                {"Protocolo", "protocolo"},
				                {"Data_manifestacao", "data_manifestacao"},
				                {"Data_finalizacao", "data_finalizacao"},
				                {"Data_revisao", "data_revisao"},
				                {"Sigla", "sigla"},
				                {"Sigilo", "sigilo"},
				                {"Dias_vida", "dias_vida"},
				                {"Dias_reativacao", "dias_reativacao"},
				                {"Dias_atraso", "dias_atraso"},
				                {"Tipo_manifestacao", "tipo_manifestacao"},
				                {"Municipio", "municipio"},
				                {"Tipificacao", "tipificacao"},
				                {"Sub_tipificacao", "sub_tipificacao"}
				            },
				            MissingField.Ignore
				        ),
				
				    // Definir tipos de dados
				    TiposDefinidos =
				        Table.TransformColumnTypes(
				            ColunasRenomeadas,
				            {
				                {"protocolo", type text},
				                {"data_manifestacao", type datetime},
				                {"data_finalizacao", type datetime},
				                {"data_revisao", type datetime},
				                {"sigla", type text},
				                {"sigilo", type text},
				                {"dias_vida", Int64.Type},
				                {"dias_reativacao", Int64.Type},
				                {"dias_atraso", Int64.Type},
				                {"tipo_manifestacao", type text},
				                {"municipio", type text},
				                {"tipificacao", type text},
				                {"sub_tipificacao", type text}
				            },
				            "pt-BR"
				        ),
				
				    // Padronizar sigla
				    SiglaPadronizada =
				        Table.ReplaceValue(
				            TiposDefinidos,
				            "GT",
				            "GOIAS TELECOM",
				            Replacer.ReplaceValue,
				            {"sigla"}
				        )
				
				in
				    SiglaPadronizada

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

