/// [Fato] Tabela central do modelo. Contém todas as manifestações registradas no SGOe — uma linha por manifestação, independente do status. Base principal para volume, tempo, procedência, recursos e relacionamento com pesquisas e respostas insatisfatórias.
table f_relatorio
	lineageTag: 1ef260cb-def5-48b1-a775-38f30eab2601

	column Id_manifestacao
		dataType: int64
		formatString: 0
		lineageTag: 7625d248-b1d8-47c2-bbd6-053dba681fba
		summarizeBy: sum
		sourceColumn: Id_manifestacao

		annotation SummarizationSetBy = Automatic

	column Protocolo
		dataType: string
		lineageTag: 73cc3a36-650c-4e71-959c-1a9cc25f3d9a
		summarizeBy: none
		sourceColumn: Protocolo

		annotation SummarizationSetBy = Automatic

	column Data_manifestacao
		dataType: dateTime
		formatString: General Date
		lineageTag: afd0acd6-0533-435c-bb49-4612188e5f92
		summarizeBy: none
		sourceColumn: Data_manifestacao

		annotation SummarizationSetBy = Automatic

	column Data_finalizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: de9e0f80-5c4f-43ba-8823-779a34cc0bfd
		summarizeBy: none
		sourceColumn: Data_finalizacao

		annotation SummarizationSetBy = Automatic

	column Data_revisao
		dataType: dateTime
		formatString: General Date
		lineageTag: c4ddc7f5-d2de-4da0-98ee-16039fa8633d
		summarizeBy: none
		sourceColumn: Data_revisao

		annotation SummarizationSetBy = Automatic

	column Sigla
		dataType: string
		lineageTag: 44e25663-6211-4bcb-b9da-4119255a59b6
		summarizeBy: none
		sourceColumn: Sigla

		annotation SummarizationSetBy = Automatic

	column Suborgao
		dataType: string
		lineageTag: 12e73efa-61d1-465b-89d4-dd8b3bb7f240
		summarizeBy: none
		sourceColumn: Suborgao

		annotation SummarizationSetBy = Automatic

	column Sigilo
		dataType: string
		lineageTag: bdd3c11d-9142-4b79-944c-a102735e1451
		summarizeBy: none
		sourceColumn: Sigilo

		annotation SummarizationSetBy = Automatic

	column Prazo_interno
		dataType: int64
		formatString: 0
		lineageTag: 423741b8-ee90-4c3c-a129-1fb651debc64
		summarizeBy: sum
		sourceColumn: Prazo_interno

		annotation SummarizationSetBy = Automatic

	column Prazo_externo
		dataType: int64
		formatString: 0
		lineageTag: bb8d102a-1d1f-4367-9455-0ca4af3d4771
		summarizeBy: sum
		sourceColumn: Prazo_externo

		annotation SummarizationSetBy = Automatic

	column Dias_vida
		dataType: int64
		formatString: 0
		lineageTag: 47187bad-8973-4d5c-a419-2bedefcee755
		summarizeBy: sum
		sourceColumn: Dias_vida

		annotation SummarizationSetBy = Automatic

	column Dias_reativacao
		dataType: int64
		formatString: 0
		lineageTag: d708c1ef-349b-40c8-90d4-daf757f476a3
		summarizeBy: sum
		sourceColumn: Dias_reativacao

		annotation SummarizationSetBy = Automatic

	column Dias_atraso
		dataType: string
		lineageTag: 99e5634e-4f84-4763-bc71-9dad124f9e88
		summarizeBy: none
		sourceColumn: Dias_atraso

		annotation SummarizationSetBy = Automatic

	column Tipo_manifestacao
		dataType: string
		lineageTag: 6e267de8-ca78-4919-866c-c6804bdcbd7d
		summarizeBy: none
		sourceColumn: Tipo_manifestacao

		annotation SummarizationSetBy = Automatic

	column Municipio
		dataType: string
		lineageTag: 76be0d25-dffa-4942-8253-c98d85792c0b
		summarizeBy: none
		sourceColumn: Municipio

		annotation SummarizationSetBy = Automatic

	column Tipificacao
		dataType: string
		lineageTag: a64e37f5-f512-4247-9495-62c98075b67a
		summarizeBy: none
		sourceColumn: Tipificacao

		annotation SummarizationSetBy = Automatic

	column Sub_tipificacao
		dataType: string
		lineageTag: e0d75001-9e68-4be1-be10-082fabd70794
		summarizeBy: none
		sourceColumn: Sub_tipificacao

		annotation SummarizationSetBy = Automatic

	column Area_tecnica
		dataType: string
		lineageTag: 3e2beee7-6773-4d2b-bc7d-0cacd12d55c5
		summarizeBy: none
		sourceColumn: Area_tecnica

		annotation SummarizationSetBy = Automatic

	column Registro
		dataType: string
		lineageTag: a4e09400-b06f-48f6-a88e-50c4f5591aa9
		summarizeBy: none
		sourceColumn: Registro

		annotation SummarizationSetBy = Automatic

	column Ds_status
		dataType: string
		lineageTag: 99ddd69d-b9bc-4073-b4af-46a32edba895
		summarizeBy: none
		sourceColumn: Ds_status

		annotation SummarizationSetBy = Automatic

	column Publicacao
		dataType: int64
		formatString: 0
		lineageTag: 11de4a0a-a0ff-489a-928d-ca5624f85fff
		summarizeBy: sum
		sourceColumn: Publicacao

		annotation SummarizationSetBy = Automatic

	column Procedente
		dataType: string
		lineageTag: 28753f69-d06c-487a-9980-a25e13eb8b0d
		summarizeBy: none
		sourceColumn: Procedente

		annotation SummarizationSetBy = Automatic

	column Recurso
		dataType: string
		lineageTag: 755a02ee-9f2f-4d51-a74f-ec8b57d7d180
		summarizeBy: none
		sourceColumn: Recurso

		annotation SummarizationSetBy = Automatic

	column Nm_sei
		dataType: string
		lineageTag: 21368455-07fd-4813-b7da-c3e0e556de1b
		summarizeBy: none
		sourceColumn: Nm_sei

		annotation SummarizationSetBy = Automatic

	partition f_relatorio = m
		mode: import
		source =
				let
				    CaminhoBase = fnCaminhoEntrada(),
				    CaminhoArquivo =
				        if Text.EndsWith(CaminhoBase, "\") or Text.EndsWith(CaminhoBase, "/")
				        then CaminhoBase & "f_relatorio.parquet"
				        else CaminhoBase & "\f_relatorio.parquet",
				
				    Fonte =
				        Parquet.Document(
				            File.Contents(CaminhoArquivo)
				        ),
				
				    #"Tipo Alterado" =
				        Table.TransformColumnTypes(
				            Fonte,
				            {
				                {"Id_manifestacao", Int64.Type},
				                {"Protocolo", type text},
				                {"Data_manifestacao", type datetime},
				                {"Data_finalizacao", type datetime},
				                {"Data_revisao", type datetime},
				                {"Sigla", type text},
				                {"Suborgao", type text},
				                {"Sigilo", type text},
				                {"Prazo_interno", Int64.Type},
				                {"Prazo_externo", Int64.Type},
				                {"Dias_vida", Int64.Type},
				                {"Dias_reativacao", Int64.Type},
				                {"Dias_atraso", type text},
				                {"Tipo_manifestacao", type text},
				                {"Municipio", type text},
				                {"Tipificacao", type text},
				                {"Sub_tipificacao", type text},
				                {"Area_tecnica", type text},
				                {"Registro", type text},
				                {"Ds_status", type text},
				                {"Publicacao", Int64.Type},
				                {"Procedente", type text},
				                {"Recurso", type text},
				                {"Nm_sei", type text}
				            }
				        ),
				
				    #"Sigla Padronizada" =
				        Table.ReplaceValue(
				            #"Tipo Alterado",
				            "GT",
				            "GOIAS TELECOM",
				            Replacer.ReplaceValue,
				            {"Sigla"}
				        )
				
				in
				    #"Sigla Padronizada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

